import type { Locale } from "@/utils/i18n";

export const WORD_BANKS: Record<Locale, string[]> = {
  en: [
    "astronaut",
    "backpack",
    "balloon",
    "banana split",
    "baseball",
    "beach chair",
    "bicycle",
    "birthday cake",
    "blanket",
    "bookstore",
    "bowling",
    "bubble tea",
    "butterfly",
    "camera",
    "campfire",
    "candle",
    "carousel",
    "castle",
    "catapult",
    "chef hat",
    "chessboard",
    "clownfish",
    "coconut",
    "compass",
    "concert",
    "cookie jar",
    "cowboy",
    "dinosaur",
    "dragon fruit",
    "drum set",
    "elevator",
    "espresso",
    "fireworks",
    "fountain",
    "frisbee",
    "giraffe",
    "glacier",
    "guitar",
    "hamburger",
    "harbor",
    "headphones",
    "helicopter",
    "ice cream",
    "island",
    "jellyfish",
    "kangaroo",
    "keyboard",
    "kite",
    "lantern",
    "lighthouse",
    "magnet",
    "microphone",
    "milkshake",
    "moonlight",
    "mountain",
    "museum",
    "noodles",
    "octopus",
    "pancakes",
    "parachute",
    "peacock",
    "piano",
    "picnic",
    "pineapple",
    "popcorn",
    "postcard",
    "pumpkin",
    "rainbow",
    "robot",
    "rocket",
    "roller skates",
    "sailboat",
    "sandcastle",
    "scarecrow",
    "school bus",
    "snow globe",
    "spaceship",
    "strawberry",
    "sunflower",
    "surfboard",
    "sushi",
    "telescope",
    "tennis racket",
    "thunderstorm",
    "toothbrush",
    "tractor",
    "treasure map",
    "trombone",
    "unicorn",
    "volcano",
    "waffles",
    "waterfall",
    "windmill",
    "wizard",
    "yogurt",
    "zeppelin"
  ],
  uz: [
    "anor",
    "samolyot",
    "velosiped",
    "muzqaymoq",
    "qal'a",
    "telefon",
    "qalam",
    "kitob",
    "oyna",
    "robot",
    "raketa",
    "traktor",
    "kapalak",
    "girafa",
    "kamalak",
    "sho'rva",
    "nonvoyxona",
    "lagan",
    "kompas",
    "musiqa",
    "gitara",
    "sharshara",
    "orol",
    "fonar",
    "mikrofon",
    "sushi",
    "pianino",
    "hamburger",
    "muzey",
    "otashfayz",
    "bulut",
    "laylak",
    "quyosh",
    "oy",
    "tog'",
    "parashyut",
    "tish cho'tka",
    "shamol tegirmoni",
    "suvosti kema",
    "qalpoq",
    "soat",
    "bodring",
    "qulupnay",
    "banan",
    "muzqaymoq aravasi",
    "futbol to'pi",
    "pechenye qutisi",
    "choynak"
  ],
  ru: [
    "арбуз",
    "велосипед",
    "самолет",
    "мороженое",
    "замок",
    "телефон",
    "карандаш",
    "книга",
    "робот",
    "ракета",
    "трактор",
    "бабочка",
    "жираф",
    "радуга",
    "гитара",
    "водопад",
    "остров",
    "фонарь",
    "микрофон",
    "пианино",
    "гамбургер",
    "музей",
    "фейерверк",
    "облако",
    "солнце",
    "луна",
    "гора",
    "парашют",
    "зубная щетка",
    "ветряная мельница",
    "подводная лодка",
    "шляпа",
    "часы",
    "огурец",
    "клубника",
    "банан",
    "чайник",
    "компас",
    "шахматы",
    "автобус",
    "суши",
    "печенье",
    "кокос",
    "фонтан",
    "рюкзак",
    "космонавт",
    "попкорн",
    "магнит"
  ]
};
